natives=Natives
vikings=Vikings
quarters=Quarters
armory=Armory
tower=Tower
ship=Ship
rock_warrior=Rock warrior
iron_warrior=Iron warrior
chicken_warrior=Chicken warrior
peon=Peon
chieftain=Chieftain
chicken_coop_natives=Chicken Coop
chicken_coop_vikings=Henhouse
totem_natives=Totem
totem_vikings=Runestone
