natives=Natives
vikings=Vikings
quarters=Quarters
armory=Armory
tower=Tower
ship=Ship
rock_warrior=Rock warrior
iron_warrior=Iron warrior
chicken_warrior=Chicken warrior
peon=Peon
chieftain=Chieftain
chicken_coop_natives=Chicken Coop
chicken_coop_vikings=Henhouse
totem_natives=Totem
totem_vikings=Runestone
shield_warrior_natives=Bark-Shield Bearer
shield_warrior_vikings=Round-Shield Carl
torch_warrior_natives=Firebrand
torch_warrior_vikings=Torchbearer
market_natives=Trading Post
market_vikings=Market
palisade_natives=Palisade
palisade_vikings=Palisade
gate_natives=Gate
gate_vikings=Gate
great_tower=Great Tower
lodge_natives=Spirit Lodge
lodge_vikings=Mead Hall
champion_natives=Headhunter
champion_vikings=Berserker
drum_warrior_natives=Drummer
drum_warrior_vikings=Hornblower
net_warrior_natives=Chicken Catcher
net_warrior_vikings=Fowler
snare=Snare
crab=Crab
monkey=Monkey
boar=Wild Boar
wolf=Wolf
